/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.NewProject;

/**
 *
 * @author saura
 */
public class Create extends javax.swing.JPanel {

    /**
     * Creates new form Create
     */
   NewProject project;
   String p;
   String DOB;
    public Create(NewProject project) {
        initComponents();
        
        this.project=project;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblgeodata = new javax.swing.JLabel();
        txtgeodata = new javax.swing.JTextField();
        lbldob = new javax.swing.JLabel();
        txtdob = new com.toedter.calendar.JDateChooser();
        lblphonenum = new javax.swing.JLabel();
        lblfax = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblmedicalnum = new javax.swing.JLabel();
        txtphonenum = new javax.swing.JTextField();
        txtmedicalnum = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        lbllinkedin = new javax.swing.JLabel();
        lblhealthnum = new javax.swing.JLabel();
        lblcertificatenum = new javax.swing.JLabel();
        lblbankacc = new javax.swing.JLabel();
        lblvehiclenum = new javax.swing.JLabel();
        lbldeviceiden = new javax.swing.JLabel();
        txtcertificatenum = new javax.swing.JTextField();
        txtbankaccn = new javax.swing.JTextField();
        txtvehiclenum = new javax.swing.JTextField();
        txtdeviceiden = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txthealthnum = new javax.swing.JTextField();
        lblip = new javax.swing.JLabel();
        lblbiometric = new javax.swing.JLabel();
        lbluin = new javax.swing.JLabel();
        txtuin = new javax.swing.JTextField();
        txtbiometric = new javax.swing.JTextField();
        txtip = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        lblErrorN = new javax.swing.JLabel();
        lblErrorT = new javax.swing.JLabel();
        lblErrorN2 = new javax.swing.JLabel();
        lblErrorE = new javax.swing.JLabel();
        lblErrorF1 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();

        jLabel1.setText("Create Profile");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblname.setText("Name");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        lblgeodata.setText("Geographic Data");

        txtgeodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeodataActionPerformed(evt);
            }
        });

        lbldob.setText("Date Of Birth");

        lblphonenum.setText("Telephone Number");

        lblfax.setText("Fax Number");

        lblemail.setText("Email Address");

        lblssn.setText("Social Security Number");

        lblmedicalnum.setText("Medical Record Number");

        txtphonenum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtphonenumKeyReleased(evt);
            }
        });

        txtfax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfaxKeyReleased(evt);
            }
        });

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        txtssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssnActionPerformed(evt);
            }
        });

        lbllinkedin.setText("Linkedin");

        lblhealthnum.setText("Health Plan Benifitiary Number");

        lblcertificatenum.setText("Certificate Number");

        lblbankacc.setText("Bank Account Number");

        lblvehiclenum.setText("Vehicle Number");

        lbldeviceiden.setText("Device Identifier");

        lblip.setText("Ip Address");

        lblbiometric.setText("Biometric");

        lbluin.setText("Unique Identifier Number");

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        lblimage.setText("Image");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                            .addComponent(lblip)
                            .addComponent(lbluin)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblname)
                                            .addComponent(lblgeodata)
                                            .addComponent(lbldob)
                                            .addComponent(lblphonenum)
                                            .addComponent(lblfax)
                                            .addComponent(lblemail)
                                            .addComponent(lblssn))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtphonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblmedicalnum)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtmedicalnum, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblhealthnum)
                                            .addComponent(lblbankacc)
                                            .addComponent(lblcertificatenum)
                                            .addComponent(lblvehiclenum)
                                            .addComponent(lbldeviceiden)
                                            .addComponent(lbllinkedin)
                                            .addComponent(lblbiometric)
                                            .addComponent(lblimage))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbankaccn)
                                            .addComponent(txthealthnum)
                                            .addComponent(txtcertificatenum)
                                            .addComponent(txtvehiclenum)
                                            .addComponent(txtdeviceiden)
                                            .addComponent(txtlinkedin)
                                            .addComponent(txtip)
                                            .addComponent(txtbiometric)
                                            .addComponent(txtuin)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnBrowse)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(lblErrorN, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblErrorE, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblErrorT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnsubmit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(425, Short.MAX_VALUE)
                    .addComponent(lblErrorN2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(183, 183, 183)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(417, Short.MAX_VALUE)
                    .addComponent(lblErrorF1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(191, 191, 191)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgeodata))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldob)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblphonenum)
                    .addComponent(txtphonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfax)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblemail)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblssn)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedicalnum)
                    .addComponent(txtmedicalnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhealthnum)
                    .addComponent(txthealthnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbankacc)
                    .addComponent(txtbankaccn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblcertificatenum))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcertificatenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblvehiclenum)
                    .addComponent(txtvehiclenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbldeviceiden))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtdeviceiden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllinkedin)
                    .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblip)
                    .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtbiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbiometric))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluin)
                    .addComponent(txtuin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimage)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnsubmit))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(lblErrorN2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(664, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(lblErrorF1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(527, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtgeodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeodataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeodataActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssnActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
   project.setName(txtname.getText());
   project.setAddress(txtgeodata.getText());
   
   
   SimpleDateFormat SD= new SimpleDateFormat("dd-MM-yyyy",Locale.getDefault());
   DOB = SD.format(txtdob.getDate());
   project.setDateOfBirth(DOB);
   
  // project.setDateOfBirth(txtdob.getDate());
   project.setPhonenum(txtphonenum.getText());
   project.setFaxnum(txtfax.getText());
   project.setEmail(txtemail.getText());
   project.setSocialsecnum(txtssn.getText());
   project.setMedicalrecnum(Integer.parseInt(txtmedicalnum.getText()));
   project.setHealthnum(Integer.parseInt(txthealthnum.getText()));
   project.setBankaccnum(Integer.parseInt(txtbankaccn.getText()));
   project.setCertificatenum(txtcertificatenum.getText());
   project.setVehiclenum(txtvehiclenum.getText());
   project.setSerialnum(Integer.parseInt(txtdeviceiden.getText()));
   project.setLinkedin(txtlinkedin.getText());
   project.setIpaddress(txtip.getText());
   project.setBiometric(txtbiometric.getText());
   project.setUniqueidentificationnumber(Integer.parseInt(txtuin.getText()));
   project.setPhoto(p);
   JOptionPane.showMessageDialog(this, "Saved");
   
   
   
   

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String P = "^[a-zA-Z\\s]{2,30}$";
        Pattern pt = Pattern.compile(P);
        Matcher match1 = pt.matcher(txtname.getText());
        if(!match1.matches()){
        lblErrorN.setText("Name is incorrect");
        }
        else{
        lblErrorN.setText(null);
        }
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtphonenumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphonenumKeyReleased
        // TODO add your handling code here:
        String P = "^[0-9]{10}$";
        Pattern pt = Pattern.compile(P);
        Matcher match1 = pt.matcher(txtphonenum.getText());
        if(!match1.matches()){
        lblErrorT.setText("Telephone number is incorrect");
        }
        else{
            lblErrorT.setText(null);
        }
    }//GEN-LAST:event_txtphonenumKeyReleased

    private void txtfaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxKeyReleased
        // TODO add your handling code here:
        String P = "^[0-9]{10}$";
        Pattern pt = Pattern.compile(P);
        Matcher match1 = pt.matcher(txtfax.getText());
        if(!match1.matches()){
        lblErrorE.setText("FAX number is incorrect");
        }
        else{
            lblErrorE.setText(null);
        }
    }//GEN-LAST:event_txtfaxKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
        String P = "^([a-zA-Z0-9.-]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9]+)+)$";
        Pattern pt = Pattern.compile(P);
        Matcher match1 = pt.matcher(txtemail.getText());
        if(!match1.matches()){
        lblErrorE.setText("Email is incorrect");
        }
        else{
            lblErrorE.setText(null);
        }
    }//GEN-LAST:event_txtemailKeyReleased

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser i = new JFileChooser();
        FileNameExtensionFilter f = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        i.addChoosableFileFilter(f);
        int showOpenDialogue = i.showOpenDialog(null);
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION){
        File c = i.getSelectedFile();
        p = c.getAbsolutePath();
    }
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblErrorE;
    private javax.swing.JLabel lblErrorF1;
    private javax.swing.JLabel lblErrorN;
    private javax.swing.JLabel lblErrorN2;
    private javax.swing.JLabel lblErrorT;
    private javax.swing.JLabel lblbankacc;
    private javax.swing.JLabel lblbiometric;
    private javax.swing.JLabel lblcertificatenum;
    private javax.swing.JLabel lbldeviceiden;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblgeodata;
    private javax.swing.JLabel lblhealthnum;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lbllinkedin;
    private javax.swing.JLabel lblmedicalnum;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphonenum;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbluin;
    private javax.swing.JLabel lblvehiclenum;
    private javax.swing.JTextField txtbankaccn;
    private javax.swing.JTextField txtbiometric;
    private javax.swing.JTextField txtcertificatenum;
    private javax.swing.JTextField txtdeviceiden;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtgeodata;
    private javax.swing.JTextField txthealthnum;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txtmedicalnum;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphonenum;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtuin;
    private javax.swing.JTextField txtvehiclenum;
    // End of variables declaration//GEN-END:variables
}
