/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import java.awt.Image;
import model.NewProject;

/**
 *
 * @author saura
 */
public class View extends javax.swing.JPanel {

    NewProject project;

    /**
     * Creates new form View
     */
    public View(NewProject project) {
        
        
        initComponents();
        this.project = project;
        View();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblgeodata = new javax.swing.JLabel();
        txtgeodata = new javax.swing.JTextField();
        lbldob = new javax.swing.JLabel();
        lblphonenum = new javax.swing.JLabel();
        lblfax = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblmedicalnum = new javax.swing.JLabel();
        txtphonenum = new javax.swing.JTextField();
        txtmedicalnum = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        lbllinkedin = new javax.swing.JLabel();
        lblhealthnum = new javax.swing.JLabel();
        lblcertificatenum = new javax.swing.JLabel();
        lblbankacc = new javax.swing.JLabel();
        lblvehiclenum = new javax.swing.JLabel();
        lbldeviceiden = new javax.swing.JLabel();
        txtcertificatenum = new javax.swing.JTextField();
        txtbankaccn = new javax.swing.JTextField();
        txtvehiclenum = new javax.swing.JTextField();
        txtdeviceiden = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txthealthnum = new javax.swing.JTextField();
        lblip = new javax.swing.JLabel();
        lblbiometric = new javax.swing.JLabel();
        lbluin = new javax.swing.JLabel();
        txtuin = new javax.swing.JTextField();
        txtbiometric = new javax.swing.JTextField();
        txtip = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        Image = new javax.swing.JLabel();
        Image1 = new javax.swing.JLabel();

        jLabel1.setText("View Profile");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblname.setText("Name");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        lblgeodata.setText("Geographic Data");

        txtgeodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeodataActionPerformed(evt);
            }
        });

        lbldob.setText("Date Of Birth");

        lblphonenum.setText("Telephone Number");

        lblfax.setText("Fax Number");

        lblemail.setText("Email Address");

        lblssn.setText("Social Security Number");

        lblmedicalnum.setText("Medical Record Number");

        txtssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssnActionPerformed(evt);
            }
        });

        lbllinkedin.setText("Linkedin");

        lblhealthnum.setText("Health Plan Benifitiary Number");

        lblcertificatenum.setText("Certificate Number");

        lblbankacc.setText("Bank Account Number");

        lblvehiclenum.setText("Vehicle Number");

        lbldeviceiden.setText("Device Identifier");

        lblip.setText("Ip Address");

        lblbiometric.setText("Biometric");

        lbluin.setText("Unique Identifier Number");

        Image.setText("Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Image))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(Image1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(383, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblname)
                                            .addComponent(lblgeodata)
                                            .addComponent(lbldob)
                                            .addComponent(lblphonenum)
                                            .addComponent(lblfax)
                                            .addComponent(lblemail)
                                            .addComponent(lblssn))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtphonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblmedicalnum)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtmedicalnum, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblhealthnum)
                                            .addComponent(lblbankacc)
                                            .addComponent(lblcertificatenum)
                                            .addComponent(lblvehiclenum)
                                            .addComponent(lbldeviceiden)
                                            .addComponent(lbllinkedin)
                                            .addComponent(lblbiometric))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbankaccn)
                                            .addComponent(txthealthnum)
                                            .addComponent(txtcertificatenum)
                                            .addComponent(txtvehiclenum)
                                            .addComponent(txtdeviceiden)
                                            .addComponent(txtlinkedin)
                                            .addComponent(txtip)
                                            .addComponent(txtbiometric)
                                            .addComponent(txtuin))))
                                .addComponent(lblip)
                                .addComponent(lbluin))
                            .addGap(0, 367, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 562, Short.MAX_VALUE)
                .addComponent(Image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Image1)
                .addGap(84, 84, 84))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblname)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblgeodata))
                    .addGap(18, 18, 18)
                    .addComponent(lbldob)
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblphonenum)
                        .addComponent(txtphonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblfax)
                        .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblemail)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblssn)
                        .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmedicalnum)
                        .addComponent(txtmedicalnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblhealthnum)
                        .addComponent(txthealthnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblbankacc)
                        .addComponent(txtbankaccn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(lblcertificatenum))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtcertificatenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblvehiclenum)
                        .addComponent(txtvehiclenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lbldeviceiden))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(txtdeviceiden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbllinkedin)
                        .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblip)
                        .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtbiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblbiometric))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbluin)
                        .addComponent(txtuin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(143, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtgeodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeodataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeodataActionPerformed

    private void txtssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblbankacc;
    private javax.swing.JLabel lblbiometric;
    private javax.swing.JLabel lblcertificatenum;
    private javax.swing.JLabel lbldeviceiden;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblgeodata;
    private javax.swing.JLabel lblhealthnum;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lbllinkedin;
    private javax.swing.JLabel lblmedicalnum;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphonenum;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbluin;
    private javax.swing.JLabel lblvehiclenum;
    private javax.swing.JTextField txtbankaccn;
    private javax.swing.JTextField txtbiometric;
    private javax.swing.JTextField txtcertificatenum;
    private javax.swing.JTextField txtdeviceiden;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtgeodata;
    private javax.swing.JTextField txthealthnum;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txtmedicalnum;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphonenum;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtuin;
    private javax.swing.JTextField txtvehiclenum;
    // End of variables declaration//GEN-END:variables

    private void View() {
    txtname.setText(project.getName());
    txtgeodata.setText(project.getAddress());
    jTextField1.setText(project.getDateOfBirth());
    //jTextField1.setText(project.getDateOfBirth());
    txtphonenum.setText(project.getPhonenum());
    txtfax.setText(project.getFaxnum());
    txtemail.setText(project.getEmail());
    txtssn.setText(project.getSocialsecnum());
    String med = Integer.toString(project.getMedicalrecnum());
    txtmedicalnum.setText(med);
    String health =Integer.toString(project.getHealthnum());
    txthealthnum.setText(health);
    String bank = Integer.toString(project.getBankaccnum());
    txtbankaccn.setText(bank);
    txtcertificatenum.setText(project.getCertificatenum());
    txtvehiclenum.setText(project.getVehiclenum());
    String seri = Integer.toString(project.getSerialnum());
    txtdeviceiden.setText(seri);
    txtlinkedin.setText(project.getLinkedin());
    txtip.setText(project.getIpaddress());
    String uni = Integer.toString(project.getUniqueidentificationnumber());
    txtuin.setText(uni);
    txtbiometric.setText(project.getBiometric());
    //Image1.setIcon(new ImageIcon(new ImageIcon(project.getPhoto()).getImage().getScaledInstance(200,200,Image.SCALE_DEFAULT))));
    Image1.setIcon(new ImageIcon(new ImageIcon(project.getPhoto()).getImage().getScaledInstance(200,200,Image.SCALE_DEFAULT)));
   // Image1.setIcon(new ImageIcon(new ImageIcon(project.ge);
    //txtimage.setText(project.getImage));
   
    
    
    
    }

}
